### ISSUE TITLE
low_probability_reply heittää erroria aina paitsi kun käyttäjä ei ole onnekas.

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#127]
low_probability_reply heittää erroria aina paitsi kun käyttäjä ei ole onnekas. Ongelma rivillä 320: 
`update.message.reply_text(None, quote=True)`

Lokit:
```
2022-02-08 20:15:55,300 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/bob/main.py", line 67, in message_handler
    low_probability_reply(update, context)
  File "/bob/main.py", line 320, in low_probability_reply
    update.message.reply_text(None, quote=True)
  File "/usr/local/lib/python3.10/site-packages/telegram/message.py", line 791, in reply_text
    return self.bot.send_message(
  File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 522, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/extbot.py", line 200, in _message
    result = super()._message(
  File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.10/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.10/site-packages/telegram/utils/request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message text is empty
```

**Comment by matiasautio** [comment]
Nice, vaihdan ton johonkin oikeaan tapaan palata tuolta funktiosta. Esim. return luulis kelpaavan.

**Comment by M4R774** [comment]
Ei tartte edes returnia, poistat vaan koko else lohkon kun se ei tee mitään.

**Comment by matiasautio** [comment]
Muistin nyt että lisäsin ton yksikkötestien takia. Tein äsken jo pull requestin ja suljin sen, mutta täytyy paremmalla ajalla katsoa kuntoon.

**Comment by M4R774** [comment]
Voit asettaa sinne mocki updateen vaan jonkun arvon ja kattoa että se ei muutu testin aikana.
