### ISSUE TITLE
Jos viestissä ei ole tekstiä, tulee erroria

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#136]
Lokeista: 
```
2022-02-11 11:21:14,595 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/bob/main.py", line 45, in message_handler
    incoming_message_text = update.message.text
AttributeError: 'NoneType' object has no attribute 'text'

```

**Comment by M4R774** [comment]
Tälle myös yksikkötesti, että ei käy näin enää jatkossa.
