### ISSUE TITLE
PTB-päivityksen ja Telethon clientin lisäysksen jälkeen havaittuja bugeja

### ISSUE THREAD

**Issue by Latemus** [M4R774/bobweb2#257]
1. Media-viestien (kuvaviestien) tekstiä ei osata käsitellä. Ongelma PTB kirjason päivityksen jälkeen jäänyt, kun sen kirjaston luokkien oliot ovat nykyään immutable. kts.  File "/bobweb/bob/message_handler.py", line 32

> AttributeError: Attribute `text` of class `Message` can't be set!
> 2023-11-08 15:51:05,591 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1069, in __create_task_callback
>     return await coroutine  # type: ignore
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_basehandler.py", line 141, in handle_update
>     return await self.callback(update, context)
>   File "/bobweb/bob/message_handler.py", line 32, in handle_update
>     update.effective_message.text = update.effective_message.caption

2. cleanup_cache funktiota kutsutaan väärin

> 2023-11-08 22:00:00,017 - apscheduler.executors.default - INFO - Running job "cleanup_cache (trigger: cron[day_of_week='sun,mon,tue,wed,thu,fri,sat', hour='0', minute='0', second='0'], next run at: 2023-11-10 00:00:00 EET)" (scheduled at 2023-11-09 00:00:00+02:00)
> 2023-11-08 22:00:00,020 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_jobqueue.py", line 800, in _run
>     await self.callback(context)
> TypeError: cleanup_cache() takes 0 positional arguments but 1 was given

3. Jos Telethon client menettää MTProto yhteyden Telegram-clienttiin, eikä sitä saada taksiin 5 uudelleenyrityksen aikana, päätyy lopulta disconectaamaan itsensä ja tappamaan koko botin event loopin

> 2023-11-08 23:48:55,445 - telegram.ext.Updater - ERROR - Error while getting Updates: Bad Gateway
> 2023-11-08 23:48:55,446 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 628, in _network_loop_retry
>     if not await action_cb():
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 333, in polling_action_cb
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_updater.py", line 322, in polling_action_cb
>     updates = await self.bot.get_updates(
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 553, in get_updates
>     updates = await super().get_updates(
>   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 394, in decorator
>     result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
>   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 3542, in get_updates
>     await self._post(
>   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 482, in _post
>     return await self._do_post(
>   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 335, in _do_post
>     return await super()._do_post(
>   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 510, in _do_post
>     return await request.post(
>   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 168, in post
>     result = await self._request_wrapper(
>   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 329, in _request_wrapper
>     raise NetworkError(description or "Bad Gateway")
> telegram.error.NetworkError: Bad Gateway
> 2023-11-09 01:01:45,146 - telethon.network.mtprotosender - INFO - Closing current connection to begin reconnect...
> 2023-11-09 01:01:45,155 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
> 2023-11-09 01:01:55,162 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
> 2023-11-09 01:02:06,171 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
> 2023-11-09 01:02:17,178 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
> 2023-11-09 01:02:28,184 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
> 2023-11-09 01:02:39,191 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
> 2023-11-09 01:02:50,198 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
> 2023-11-09 01:02:51,201 - telethon.network.mtprotosender - INFO - Failed reconnection attempt 1 with ConnectionError
> 2023-11-09 01:02:52,203 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
> 2023-11-09 01:03:02,207 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
> 2023-11-09 01:03:13,214 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
> 2023-11-09 01:03:24,221 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
> 2023-11-09 01:03:35,228 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
> 2023-11-09 01:03:46,235 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
> 2023-11-09 01:03:57,244 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
> 2023-11-09 01:03:58,247 - telethon.network.mtprotosender - INFO - Failed reconnection attempt 2 with ConnectionError
> 2023-11-09 01:03:59,250 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
> 2023-11-09 01:04:09,255 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
> 2023-11-09 01:04:20,263 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
> 2023-11-09 01:04:31,272 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
> 2023-11-09 01:04:42,281 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
> 2023-11-09 01:04:53,287 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
> 2023-11-09 01:05:04,295 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
> 2023-11-09 01:05:05,298 - telethon.network.mtprotosender - INFO - Failed reconnection attempt 3 with ConnectionError
> 2023-11-09 01:05:06,300 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
> 2023-11-09 01:05:16,305 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
> 2023-11-09 01:05:27,315 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
> 2023-11-09 01:05:38,321 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
> 2023-11-09 01:05:49,328 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
> 2023-11-09 01:06:00,340 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
> 2023-11-09 01:06:11,347 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
> 2023-11-09 01:06:12,350 - telethon.network.mtprotosender - INFO - Failed reconnection attempt 4 with ConnectionError
> 2023-11-09 01:06:13,354 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
> 2023-11-09 01:06:23,359 - telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError:
> 2023-11-09 01:06:34,366 - telethon.network.mtprotosender - WARNING - Attempt 2 at connecting failed: TimeoutError:
> 2023-11-09 01:06:45,373 - telethon.network.mtprotosender - WARNING - Attempt 3 at connecting failed: TimeoutError:
> 2023-11-09 01:06:56,380 - telethon.network.mtprotosender - WARNING - Attempt 4 at connecting failed: TimeoutError:
> 2023-11-09 01:07:07,389 - telethon.network.mtprotosender - WARNING - Attempt 5 at connecting failed: TimeoutError:
> 2023-11-09 01:07:18,395 - telethon.network.mtprotosender - WARNING - Attempt 6 at connecting failed: TimeoutError:
> 2023-11-09 01:07:19,398 - telethon.network.mtprotosender - INFO - Failed reconnection attempt 5 with ConnectionError
> 2023-11-09 01:07:20,401 - telethon.network.mtprotosender - ERROR - Automatic reconnection failed 5 time(s)
> 2023-11-09 01:07:20,403 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.92:443/TcpFull...
> 2023-11-09 01:07:20,404 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.92:443/TcpFull complete!
> 2023-11-09 01:07:20,409 - asyncio - ERROR - Future exception was never retrieved
> future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
> ConnectionError: Connection to Telegram failed 5 time(s)
> 2023-11-09 01:07:20,413 - telethon.network.mtprotosender - INFO - Not disconnecting (already have no connection)
> 2023-11-09 01:07:20,472 - telegram.ext.Application - WARNING - Fetching updates got a asyncio.CancelledError. Ignoring as this task may onlybe closed via `Application.stop`.

**Comment by Latemus** [comment]
1 ja 2 korjattu. Kohta 3 vielä auki.
